#!/usr/bin/env bash

set -euf

# Define variables
feature_branch="my-nixos-unstable"
date=$(date +"%Y-%m-%d")
time=$(date +"%H%M")
tag_name="${feature_branch}_before_rebase_${date}_${time}"

# Verify current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "$feature_branch" ]; then
    echo "Error: Not on $feature_branch branch. Aborting."
    exit 1
fi

git fetch upstream/nixos-unstable

# Create tag
git tag "$tag_name"

# Rebase on master, this should fail sometimes, u've to edit files and then do the push manually
git rebase upstream/nixos-unstable

# have to use --force because since what I get wasn't applied on top of my commits(ie. they upstream didn't rebase on top of my last push) then theirs has diverged from what I pushed, so i've to go back in time, find common base, and all my commits will have to be re-applied on their latest commit.
git push --force origin "$feature_branch"

echo "All done."
